apiVersion: v1
kind: Service

metadata:
  name: profile-monitoring

spec:
  # Headless Service.
  # Не имеет собственного IP-адреса и предоставляет список Pod'ов (Endpoints),
  # что позволяет Prometheus собирать метрики с каждой реплики отдельно.
  clusterIP: None

  # Service находит Pod'ы с данной меткой
  selector:
    app: profile-service

  ports:
    # Порт Spring Boot Actuator
    - name: actuator

      # Порт Service
      port: 8080

      # Порт контейнера с Actuator
      targetPort: 8080

    # Порт Java Agent
    - name: agent

      # Порт Service
      port: 9911

      # Порт контейнера, на котором Java Agent публикует метрики
      targetPort: 9911