services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "9911:9911"
    volumes:
      - app-logs:/var/log/app
      - ./service/src/main/resources/schemas:/app/schemas
    environment:
      - SCANNING_PACKAGES=app.project_profile,app.project_profile.api.,app.project_profile.application.
      - PATHTOJSON=/app/schemas/
    depends_on:
      - logstash

  filebeat:
    build:
      context: .
      dockerfile: Dockerfile.filebeat
    user: root
    volumes:
      - app-logs:/var/log/app:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - filebeat-data:/usr/share/filebeat/data
    depends_on:
      - logstash
    command: [ "--strict.perms=false" ]
    networks:
      - test-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - test-net

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.3
    container_name: logstash
    depends_on:
      - elasticsearch
    ports:
      - "5044:5044"
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    command:
    networks:
      - test-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.3
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - test-net

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - project_profile_redis_data:/data
    command: redis-server --requirepass semechko --save 60 1 --loglevel warning
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "semechko", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    build: './config/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus

  mock-external-system:
    build: ./nginx
    ports:
      - "8081:80"
    restart: unless-stopped

volumes:
  app-logs:
  filebeat-data:
  project_profile_redis_data:
  elasticsearch-data:

networks:
  monitoring:
  test-net:
    driver: bridge