FROM docker.elastic.co/beats/filebeat:8.15.0

USER root

COPY filebeat/filebeat.yml /usr/share/filebeat/filebeat.yml
RUN chmod 644 /usr/share/filebeat/filebeat.yml

ENTRYPOINT ["/usr/local/bin/docker-entrypoint", "-e", "--strict.perms=false"]