spring:
  application:
    name: service

 # настройки для Redis
  data:
    redis:
      host: redis
      port: 6379
      password: semechko

# настройки Actuator
management:
  metrics:
    distribution:
      percentiles:
        external.echo.request.time: 0.0
        http.server.requests: 0.0
  endpoints:
    web:
      exposure:
        include: prometheus

# Logging pattern
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [uri=%X{uri}] - %msg%n"

# адрес echo service для k8s и docker
#mockExternalSystemUrl: http://echo-service:80
mockExternalSystemUrl: http://mock-external-system:80

server:
  port: 8080
  servlet:
    context-path: /api