spring:
  application:
    name: service

  data:
    redis:
      host: redis
      port: 6379
      password: semechko

management:
  metrics:
    distribution:
      percentiles:
        external.echo.request.time: 0.0
        http.server.requests: 0.0
  endpoints:
    web:
      exposure:
        include: prometheus

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [uri=%X{uri}] - %msg%n"

pathToJson: ./src/main/resources/schemas/

server:
  port: 8080
  servlet:
    context-path: /api