apiVersion: v1
kind: Service

metadata:
  name: echo-service

spec:
  # Service направляет трафик на поды с данной меткой
  selector:
    app: echo-service

  ports:
    - name: http
      # Порт, по которому Service доступен внутри Kubernetes
      port: 80
      # Порт контейнера, на который проксируются запросы
      targetPort: 80