apiVersion: apps/v1
kind: Deployment

metadata:
  name: echo-service

spec:
  replicas: 1

  # Deployment управляет подами с этой меткой
  selector:
    matchLabels:
      app: echo-service

  # Шаблон создаваемых подов
  template:
    metadata:
      labels:
        app: echo-service

    spec:
      containers:
        - name: echo-service
          image: project_profile-mock-external-system:latest

          # Использовать локальный образ (minikube)
          imagePullPolicy: Never

          # ограничения по ресурсам
          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"

            limits:
              memory: "128Mi"
              cpu: "200m"

          # Порт, который прослушивает приложение внутри контейнера
          ports:
            - containerPort: 80