apiVersion: apps/v1
kind: Deployment

metadata:
  name: echo-service

spec:
  replicas: 1

  selector:
    matchLabels:
      app: echo-service

  template:
    metadata:
      labels:
        app: echo-service

    spec:
      containers:
        - name: echo-service
          image: project_profile-mock-external-system:latest

          imagePullPolicy: Never

          resources:
            requests:
              memory: "32Mi"
              cpu: "50m"

            limits:
              memory: "128Mi"
              cpu: "200m"

          ports:
            - containerPort: 80