apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:8.17.3

          env:
            - name: NODE_OPTIONS
              value: "--max-old-space-size=512"
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200

          resources:
            requests:
              memory: "512Mi"
              cpu: "200m"

            limits:
              memory: "1Gi"
              cpu: "1000m"

          ports:
            - containerPort: 5601