apiVersion: v1
kind: Service

metadata:
  name: grafana
  labels:
    app: grafana

spec:
  type: ClusterIP

  # Service направляет трафик на поды с данной меткой
  selector:
    app: grafana

  ports:
    # Порт, по которому Service доступен внутри Kubernetes
    - port: 3000
    # Порт контейнера, на который проксируются запросы
      targetPort: 3000
      protocol: TCP