apiVersion: apps/v1

kind: Deployment

metadata:
  name: grafana
  labels:
    app: grafana

spec:
  replicas: 1

  # Deployment управляет подами с этой меткой
  selector:
    matchLabels:
      app: grafana

  # Шаблон создаваемых подов
  template:
    metadata:
      labels:
        app: grafana

    spec:
      containers:
        - name: grafana
          image: grafana-custom:latest

          # Использовать локальный образ (minikube)
          imagePullPolicy: Never

          ports:
            - containerPort: 3000

          # Переменные окружения контейнера
          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "admin"
            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "admin"

          # ограничения по ресурсам
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "500m"