input {
  beats {
    port => 5044
  }
}

filter {
  mutate {
    # удаляем поля которые шлёт logstash в elasticsearch
    remove_field => ["agent", "ecs", "input", "log", "host"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "spring-logs-%{+YYYY.MM.dd}"
  }
}