apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config

data:
  logstash.conf: |
    input {
      tcp {
      port => 5044
      codec => json_lines
      }
    }

    filter {
      mutate {
        remove_field => ["agent", "ecs", "input", "log", "host"]
      }
    }

    output {
      stdout {
        codec => rubydebug
      }
    
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "spring-logs-%{+YYYY.MM.dd}"
      }
    }